services:
  - type: web
    name: smart-city-online
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python online_app.py
    envVars:
      - key: ELASTICSEARCH_INDEX
        value: smart-city-unified
      - key: ELASTICSEARCH_URL
        sync: false
      - key: ELASTICSEARCH_USERNAME
        sync: false
      - key: ELASTICSEARCH_PASSWORD
        sync: false
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_USERNAME
        sync: false
      - key: KAFKA_PASSWORD
        sync: false
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN
      - key: KAFKA_SSL_CA_PEM
        sync: false
      - key: WAQI_TOKEN
        sync: false
